[workspace]
authors = ["pranav-cheraku <pranavcheraku@gmail.com>"]
channels = ["robostack-humble", "conda-forge"]
name = "my_ros2_project"
platforms = ["osx-arm64"]
version = "0.1.0"

[tasks]

[dependencies]
ros-humble-desktop = ">=0.10.0,<0.11"
